import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("production surface uses an injected exact commerce origin without an iframe broker", async () => {
  const app = await readFile(new URL("../app.js", import.meta.url), "utf8");
  const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
  const build = await readFile(new URL("../scripts/build.mjs", import.meta.url), "utf8");
  const sitesBuild = await readFile(new URL("../scripts/prepare-sites.mjs", import.meta.url), "utf8");
  const sitesPage = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const intentRoute = await readFile(new URL("../app/intent/route.ts", import.meta.url), "utf8");
  const profileRoute = await readFile(new URL("../app/.well-known/ucp/route.ts", import.meta.url), "utf8");
  const toolContracts = await readFile(new URL("../lib/webmcp-tool-contracts.js", import.meta.url), "utf8");
  const layout = await readFile(new URL("../app/layout.tsx", import.meta.url), "utf8");
  assert.doesNotMatch(app, /127\.0\.0\.1/);
  assert.match(html, /<script src="\/config\.js"><\/script>/);
  assert.doesNotMatch(html, /<iframe/);
  assert.doesNotMatch(app, /vaultOrigin|discloseThroughVault/);
  assert.doesNotMatch(app, /modelContext\?\.executeTool|modelContext\?\.getTools/);
  assert.match(toolContracts, /ACTION_TOOL = "intent_open_approved_checkout_once"/);
  assert.match(toolContracts, /name: "intent_stage_candidate_for_approval"/);
  assert.match(app, /const decision=await waitForHumanApproval\(proposal,signal\)/);
  assert.match(app, /no follow-up chat message needed/i);
  assert.match(app, /settlePendingApproval\(\{outcome:"granted"/);
  assert.match(app, /state\.staged\?\.mandateVersion!==state\.mandateVersion/);
  assert.match(app, /WebMCP agent connected/);
  assert.match(app, /Browsing mode/);
  assert.match(app, /Open Intent in a WebMCP-enabled client to collaborate with your agent\./);
  assert.match(html, /Live commerce · explicit authority/);
  assert.match(html, /No capability exists/);
  assert.match(html, /One use, 60 seconds, then gone/);
  assert.match(app, /Searching live merchants/);
  assert.match(app, /Applying mandate rules/);
  assert.match(app, /Ranking eligible offers/);
  assert.equal(toolContracts.match(/untrustedContentHint: true/g)?.length, 5);
  assert.match(app, /via WebMCP/);
  assert.match(app, /readback:mutationReadback\(\)/);
  assert.match(app, /createResumeSnapshot, parseResumeSnapshot/);
  assert.match(app, /session:plan\.session/);
  assert.match(app, /clearSafeResume\(\);resetCapabilityLedger/);
  assert.match(app, /checkout authority absent/);
  assert.doesNotMatch(app, /fake progress|\d+% complete/i);
  assert.doesNotMatch(html, /Universal agentic commerce|impossible to quietly exceed/i);
  assert.doesNotMatch(build, /INTENT_VAULT_ORIGIN/);
  assert.match(sitesBuild, /process\.env\.INTENT_COMMERCE_ORIGIN/);
  assert.match(sitesBuild, /exact HTTP\(S\) origin/);
  assert.doesNotMatch(sitesBuild, /intent\.html/);
  assert.match(sitesPage, /window\.location\.replace\("\/intent"\)/);
  assert.match(intentRoute, /export const dynamic = "force-dynamic"/);
  assert.match(intentRoute, /Content-Security-Policy/);
  assert.match(intentRoute, /frame-ancestors 'self'/);
  assert.match(intentRoute, /Permissions-Policy/);
  assert.match(profileRoute, /Access-Control-Allow-Origin/);
  assert.match(profileRoute, /public, max-age=300/);
  assert.match(layout, /metadataBase:\s*new URL\("https:\/\/intent-commerce\.gowtham0992\.chatgpt\.site"\)/);
});

test("production hosts allowlist only the exact app and commerce origins", async () => {
  const commerce = await readFile(new URL("../wrangler.commerce.jsonc", import.meta.url), "utf8");
  const vercel = await readFile(new URL("../vercel.json", import.meta.url), "utf8");
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const plugin = await readFile(new URL("../plugins/intent/skills/intent-shopping/SKILL.md", import.meta.url), "utf8");
  assert.match(commerce, /https:\/\/intent-lime-five\.vercel\.app/);
  assert.match(commerce, /\.well-known\/ucp/);
  assert.match(vercel, /https:\/\/intent-commerce\.gowtham0992\.workers\.dev/);
  assert.match(readme, /https:\/\/intent-commerce\.gowtham0992\.chatgpt\.site\/intent/);
  assert.match(plugin, /https:\/\/intent-commerce\.gowtham0992\.chatgpt\.site\/intent/);
  assert.doesNotMatch(vercel, /intent-vault/);
  assert.doesNotMatch(`${commerce}\n${vercel}`, /http:\/\//);
});
